In [1]:
#BP神经网络：异或问题，即线性不可分类问题
import numpy as np
#输入
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#输出
Y = np.array([[0,1,1,0]])
#输入层到隐藏层权值
V = np.random.random((3,4))*2 - 1
#隐藏层到输出层权值（由于这里的BP只有两个隐藏层）
W = np.random.random((4,1))*2 - 1
print(V)
print(W)
#学习率
lr = 0.11
#定义激活函数
def sigmoid(x):
    return 1/(1+np.exp(-x))
#激活函数的导数，会用到
def dsigmoid(x):
    return x*(1-x)
#定义更新权值函数
def update():
    global X,Y,V,W,lr
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
    #接下来是关键点
    L2_delta = (Y.T - L2) * dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T) * dsigmoid(L1)

    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)

    W = W + W_C
    V = V + V_C
#迭代
for i in range(20000):
    update()
    if i % 500 ==0:
        L1 = sigmoid(np.dot(X, V))  # 隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1, W))  # 输出层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T-L2)))

L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
print(L2)
#最终输出判断
def judge(x):
    if x > 0.5:
        return 1
    else:
        return 0
for i in map(judge,L2):
    print(i)

[[-0.66898165 -0.19698606 -0.67728269  0.57806033]
 [ 0.31149895  0.99892429 -0.74996323  0.81609688]
 [ 0.1241127  -0.91504354  0.33791426 -0.06046124]]
[[ 0.62567477]
 [-0.77735897]
 [-0.82051022]
 [ 0.79709225]]
Error: 0.5019733165126559
Error: 0.49581677927054857
Error: 0.4806202078744883
Error: 0.43168971495356245
Error: 0.3279038720268713
Error: 0.2037975430368641
Error: 0.14107108602313853
Error: 0.10995531104577233
Error: 0.09174359303128313
Error: 0.07973734765046706
Error: 0.07116596252244319
Error: 0.06469769273653464
Error: 0.05961512189512275
Error: 0.0554972491309854
Error: 0.052080240556044106
Error: 0.049189974699729105
Error: 0.04670664497345399
Error: 0.04454494451685219
Error: 0.04264236878025561
Error: 0.04095199698957307
Error: 0.03943786699349785
Error: 0.03807191475858111
Error: 0.036831891881521014
Error: 0.03569991356360348
Error: 0.034661424145874774
Error: 0.03370444589726852
Error: 0.03281902408890013
Error: 0.03199681071420214
Error: 0.03123074784322951
Err