In [1]:
#BP神经网络：异或问题，即线性不可分类问题
import numpy as np
#输入
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#输出
Y = np.array([[0,1,1,0]])
#输入层到隐藏层权值
V = np.random.random((3,4))*2 - 1
#隐藏层到输出层权值（由于这里的BP只有两个隐藏层）
W = np.random.random((4,1))*2 - 1
print(V)
print(W)
#学习率
lr = 0.11
#定义激活函数
def sigmoid(x):
    return 1/(1+np.exp(-1))
#激活函数的导数，会用到
def dsigmoid(x):
    return x*(1-x)
#定义更新权值函数
def update():
    global X,Y,V,W,lr
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
    #接下来是关键点
    L2_delta = (Y.T - L2)* dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T) * dsigmoid(L1)

    W_C = lr*(L1.T).dot(L2_delta)
    V_C = lr*(X.T).dot(L1_delta)

    W_C = W + W_C
    V_C = V + V_C
#迭代
for i in range(20000):
    update()
    if i % 500 ==0:
        L1 = sigmoid(np.dot(X, V))  # 隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1, W))  # 输出层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T-L2)))

L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
print(L2)

[[-0.2630656   0.39223107 -0.12311719 -0.47270487]
 [-0.04847142  0.2148489   0.60305302  0.18246759]
 [-0.80101734 -0.15994824  0.38446514  0.08272841]]
[[ 0.16377667]
 [ 0.69344137]
 [-0.20117854]
 [-0.72323038]]


AttributeError: 'numpy.float64' object has no attribute 'dot'